version: "3"
services:
    argon2:
        build:
            context: "."
            dockerfile: "./docker/argon2/Dockerfile"
        image: "watcoin:argon2"
    bitcoind:
        build:
            context: "."
            dockerfile: "./docker/bitcoind/Dockerfile"
        command: ["-rpcallowip=0.0.0.0/0", "-rest"]
        depends_on:
         - "argon2"
        env_file:
         - "./.env"
        expose:
         - "${BITCOIN_PORT}"
         - "${BITCOIN_RPC_PORT}"
        hostname: "watcoin:bitcoind"
        image: "watcoin:bitcoind"
        volumes:
         - "./data/bitcoind:${BITCOIN_DATA_DIR}"
    cpuminer:
        build:
            context: "."
            dockerfile: "./docker/cpuminer/Dockerfile"
        depends_on:
         - "bitcoind"
        env_file:
         - "./.env"
        hostname: "watcoin:cpuminer"
        image: "watcoin:cpuminer"
    qt:
        build:
            context: "."
            dockerfile: "./docker/qt/Dockerfile"
        depends_on:
         - "argon2"
        env_file:
         - "./.env"
        expose:
         - "${BITCOIN_PORT}"
         - "${BITCOIN_RPC_PORT}"
        hostname: "watcoin:qt"
        image: "watcoin:qt"
        volumes:
         - "./data/qt:${BITCOIN_DATA_DIR}"
         - "/tmp/.X11-unix:/tmp/.X11-unix"
