version: '3'
services:
    watcoin-bitcoind0:
      image: "watcoin:bitcoind"
      environment:
        BITCOIN_PORT: 8686
        BITCOIN_RPC_PORT: 8787
        BITCOIN_RPC_DEPRECATED: "generate"
        BITCOIN_REGTEST: 1
        BITCOIN_DATA_DIR: "/data"
        BITCOIN_DNS: ""
      restart: "always"
    watcoin-bitcoind1:
      image: "watcoin:bitcoind"
      environment:
        BITCOIN_PORT: 8686
        BITCOIN_RPC_PORT: 8787
        BITCOIN_RPC_DEPRECATED: "generate"
        BITCOIN_REGTEST: 1
        BITCOIN_DATA_DIR: "/data"
        BITCOIN_CONNECT: "watcoin-bitcoind0:8686"
        BITCOIN_DNS: ""
      depends_on:
       - "watcoin-bitcoind0"
    watcoin-bitcoind2:
      image: "watcoin:bitcoind"
      environment:
        BITCOIN_PORT: 8686
        BITCOIN_RPC_PORT: 8787
        BITCOIN_RPC_DEPRECATED: "generate"
        BITCOIN_REGTEST: 1
        BITCOIN_DATA_DIR: "/data"
        BITCOIN_CONNECT: "watcoin-bitcoind0:8686"
        BITCOIN_DNS: ""
      depends_on:
       - "watcoin-bitcoind0"
